name: "Tauri Build"

on:
  push:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: intl, fileinfo
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          npm install

      - name: build app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'SIPETA v__VERSION__'
          releaseBody: 'Automated desktop build for SIPETA.'
          releaseDraft: false
          prerelease: false
          projectPath: "src-tauri"
